from backporter.Models      import DistType, BackportStatus

dists =(('etch',
         DistType.Released.Value,
         'http://ftp.it.debian.org/debian',
         'main contrib non-free'),
        ('sid', 
         DistType.Bleeding.Value,
         'http://ftp.it.debian.org/debian',
         'main contrib non-free'),
        ('local',
         DistType.Bleeding.Value,
         'http://apt.64studio.com/backports',
         'main'),
        ('gutsy', 
         DistType.Released.Value,
         'http://archive.ubuntu.com/ubuntu',
         'main restricted multiverse universe'))

bkps = [('libgig', BackportStatus.AutoUpdate.Value, {'dist':'etch','arch':'i386'}),
        ('qtractor', BackportStatus.AutoUpdate.Value, None),
        ('wine', BackportStatus.AutoUpdate.Value, None),
        ('jackeq', BackportStatus.AutoUpdate.Value, None),
        ('ekiga',BackportStatus.AutoUpdate.Value,None)]

src = [('libgig', 'etch', '0.1'),
       ('liblscp', 'sid', '0.2')]

pkgs  = [(-1, 'libgig', '0.1', '1'),
         (-1, 'liblscp', '0.1', '3')]

jobs  = [(-1, 0, 'a', 1, 'etch', 'i386', 'a', 'a', 'a', 'a', 'a'),
         (-1, 0, 'a', 2, 'etch', 'amd64', 'a', 'a', 'a', 'a', 'a')]

pkgs_many = [
('aeolus','0.6.6+2-4~bpo.1',BackportStatus.AutoUpdate.Value),
('alsa-driver','1.0.14-2~etch1',BackportStatus.AutoUpdate.Value),
('alsa-firmware','1.0.15-1~etch1',BackportStatus.AutoUpdate.Value),
('ams','1.8.8~rc2-2~etch1',BackportStatus.AutoUpdate.Value),
('freecycle','0.6alpha-2~bpo.1',BackportStatus.Freezed.Value),
('fst','1.9-3~etch1',BackportStatus.Freezed.Value),
('fusd-kor','1.10+11-2~etch1',BackportStatus.Freezed.Value),
('gail','1.20.0-1~bpo.1',BackportStatus.Freezed.Value),
('gavl','0.2.5-1~bpo.1',BackportStatus.AutoUpdate.Value),
('glashctl','0.4.2-4~bpo.1',BackportStatus.AutoUpdate.Value),
('glib2.0','2.14.2-1~etch1',BackportStatus.Freezed.Value),
('glibmm2.4','2.12.9-0.1~bpo.1',BackportStatus.Freezed.Value),
('gnomad2','2.8.12-2~etch1',BackportStatus.Freezed.Value),
('gnome-bluetooth','0.9.1-1~bpo.1',BackportStatus.Freezed.Value),
('gnome-icon-theme','2.18.0-2~bpo.1',BackportStatus.Freezed.Value),
('gnome-icon-theme-yasis','0.4.2-1~etch1',BackportStatus.Freezed.Value),
('gnome-media','2.18.0-2~bpo.1',BackportStatus.Freezed.Value),
('gnome-pkg-tools','0.12.3~bpo.1',BackportStatus.Freezed.Value),
('gnome-system-tools','2.18.1-1~bpo.1',BackportStatus.Freezed.Value),
('gnome-themes','2.18.1-2~bpo.1',BackportStatus.Freezed.Value),
('gnome-vfs2','2.20.0-1~bpo.1',BackportStatus.Freezed.Value),
('gstreamer0.10','0.10.12-5~bpo.1',BackportStatus.Freezed.Value),
('gtk+2.0','2.10.13-1~bpo.1',BackportStatus.Freezed.Value),
('gtk2-engines','2.12.1-1~etch1',BackportStatus.Freezed.Value),
('gtkmm2.4','2.10.10-0.2~bpo.1',BackportStatus.Freezed.Value),
('hexter','0.6.1-2~bpo.1',BackportStatus.AutoUpdate.Value),
('hvirtual','2.1.0-2svn20070109~bpo.1',BackportStatus.Freezed.Value),
('hydrogen','0.9.3-4~bpo.1',BackportStatus.Freezed.Value),
('hydrogen-drumkits','0.9.3.20070703-1~bpo.1',BackportStatus.AutoUpdate.Value),
('ia32-libs-gtk','1.0~bpo.1',BackportStatus.Freezed.Value),
('idjc','0.7.0a-1~bpo.1',BackportStatus.Freezed.Value),
('inkscape','0.45.1-1~bpo.1',BackportStatus.AutoUpdate.Value),
('intltool','0.36.2-1~bpo.1',BackportStatus.Freezed.Value),
('jack-audio-connection-kit','0.103.0-6~bpo.1',BackportStatus.AutoUpdate.Value),
('jackdmp','0.62-1~bpo.1',BackportStatus.AutoUpdate.Value),
('jack-rack','1.4.5-1+cvs070713~bpo.1',BackportStatus.Freezed.Value),
('jamin','0.95.0-4~etch1',BackportStatus.Freezed.Value),
('k3d','0.6.6.0.ds1-1~bpo.1',BackportStatus.Freezed.Value),
('kmidimon','0.5.0-2~etch1',BackportStatus.Freezed.Value),
('ktoon','0.8.1-1~bpo.1',BackportStatus.AutoUpdate.Value),
('lash','0.5.3-2~bpo.1',BackportStatus.AutoUpdate.Value),
('libart-lgpl','2.3.19-3~bpo.1',BackportStatus.Freezed.Value),
('libbonobo','2.20.0-1~bpo.1',BackportStatus.Freezed.Value),
('libbonoboui','2.20.0-1~bpo.1',BackportStatus.Freezed.Value),
('libbtctl','0.9.0-2~bpo.1',BackportStatus.Freezed.Value),
('libcairo','1.4.10-1~etch1',BackportStatus.Freezed.Value),
('libdatrie','0.1.2-2~bpo.1',BackportStatus.Freezed.Value),
('libfreebob','1.0.3+svn443-2~bpo.1',BackportStatus.Freezed.Value),
('libgig','3.2.0-0.1~etch1',BackportStatus.Freezed.Value),
('libglade2','2.6.2-1~bpo.1',BackportStatus.Freezed.Value),
('libgnome','2.20.0-1~bpo.1',BackportStatus.Freezed.Value),
('libgnomecanvas','2.20.0-1~bpo.1',BackportStatus.Freezed.Value),
('libgnomeui','2.18.1-2~bpo.1',BackportStatus.Freezed.Value),
('liblscp','0.5.5-0.1~etch1',BackportStatus.Freezed.Value),
('libmtp','0.2.2-2~etch1',BackportStatus.Freezed.Value),
('libnet-dbus-perl','0.33.4-1~bpo.1',BackportStatus.Freezed.Value),
('liboobs','2.18.1-2~bpo.1',BackportStatus.Freezed.Value),
('librsvg','2.16.1-2~bpo.1',BackportStatus.Freezed.Value),
('libthai','0.1.9-1~etch1',BackportStatus.Freezed.Value),
('libwmf','0.2.8.4-6~bpo.1',BackportStatus.Freezed.Value),
('libxml2','2.6.30.dfsg-2~bpo.1',BackportStatus.Freezed.Value),
('libxslt','1.1.22-1~bpo.1',BackportStatus.Freezed.Value),
('linux-kbuild-2.6','2.6.22-1~bpo.1',BackportStatus.Freezed.Value),
('linuxsampler','0.5.0-2~etch1',BackportStatus.Freezed.Value),
('ll-scope','0.2.1-2~bpo.1',BackportStatus.Freezed.Value),
('mhwaveedit','1.4.13-1~bpo.1',BackportStatus.AutoUpdate.Value),
('midisport-firmware','1.2-1~bpo.1',BackportStatus.Freezed.Value),
('mplayer','1.0~rc1-16.1~bpo.1',BackportStatus.Freezed.Value),
('nekobee','0.1.6-1~bpo.1',BackportStatus.AutoUpdate.Value),
('nvidia-graphics-drivers','1.0.9755-1~bpo.1',BackportStatus.Freezed.Value),
('nvidia-graphics-drivers-legacy-71xx','1.0.7185-3~bpo.1',BackportStatus.Freezed.Value),
('nvidia-graphics-drivers-legacy-96xx','1.0.9631-3~bpo.1',BackportStatus.Freezed.Value),
('opal','2.2.8~dfsg1-2~bpo.1',BackportStatus.Freezed.Value),
('openmovieeditor','0.0.20061221-4~bpo.1',BackportStatus.Freezed.Value),
('oss2jack','0.25-1~bpo.1',BackportStatus.Freezed.Value),
('pango1.0','1.18.2-2~etch1',BackportStatus.Freezed.Value),
('pcre3','7.3-2~etch1',BackportStatus.Freezed.Value),
('poppler','0.5.4-2~bpo.1',BackportStatus.Freezed.Value),
('puredata','0.40.2-2~bpo.1',BackportStatus.Freezed.Value),
('pwlib','1.10.7~dfsg1-4~bpo.1',BackportStatus.Freezed.Value),
('pygobject','2.12.3-2~bpo.1',BackportStatus.Freezed.Value),
('pygtk','2.10.6-1~bpo.1',BackportStatus.Freezed.Value),
('python-distutils-extra','1.90~bpo.1',BackportStatus.Freezed.Value),
('qjackctl','0.2.22-2~bpo.1',BackportStatus.Freezed.Value),
('qsampler','0.1.5-1~etch1',BackportStatus.Freezed.Value),
('qtractor','0.0.6.728-1~etch1',BackportStatus.Freezed.Value),
('rosegarden','1:1.5.1-3~etch1',BackportStatus.Freezed.Value),
('scribus','1.3.3.9.dfsg-1~bpo.1',BackportStatus.Freezed.Value),
('scribus-ng','1.3.4.dfsg-1~bpo.1',BackportStatus.Freezed.Value),
('sineshaper','0.4.2-4~bpo.1',BackportStatus.Freezed.Value),
('sound-juicer','2.16.4-1~bpo.1',BackportStatus.Freezed.Value),
('splix','1.0.1-1~bpo.1',BackportStatus.Freezed.Value),
('squashfs','3.2r2-6~bpo.1',BackportStatus.Freezed.Value),
('stopmotion','0.6.0-1~bpo.2',BackportStatus.AutoUpdate.Value),
('stops','0.3.0-1~bpo.1',BackportStatus.AutoUpdate.Value),
('swh-plugins','0.4.15-0.1~bpo.1',BackportStatus.AutoUpdate.Value),
('synaptic','0.60~bpo.1',BackportStatus.Freezed.Value),
('sysinfo','0.7-1~bpo.1',BackportStatus.Freezed.Value),
('system-tools-backends','2.2.1-2~bpo.1',BackportStatus.Freezed.Value),
('sysv-rc-bootsplash','1.0.5-4~etch1',BackportStatus.Freezed.Value),
('tasksel','2.68~bpo.1',BackportStatus.Freezed.Value),
('vkeybd','1:0.1.17b-1~bpo.1',BackportStatus.AutoUpdate.Value),
('wine','0.9.47-1~bpo.1',BackportStatus.Freezed.Value),
('wineasio','0.5-1~bpo.1',BackportStatus.Freezed.Value),
('wsynth-dssi','0.1.3-2~etch1',BackportStatus.AutoUpdate.Value),
('xaralx','0.7r1692-2~etch1',BackportStatus.AutoUpdate.Value),
('xsynth-dssi','0.9.0-2~etch1',BackportStatus.AutoUpdate.Value),
('youtube-dl','2007.08.24-1~bpo.1',BackportStatus.AutoUpdate.Value),
('zynaddsubfx-text','2.2.1-2~etch1',BackportStatus.AutoUpdate.Value),
]
